### ISSUE TITLE
libmwdastudio.so

### ISSUE THREAD

**Issue by somalcy** [rdiggelmann/HDsort#1]
when I use matlab2017a to run this line `HDSorting.preprocess('chunkSize', chunkSize, 'forceFileDeletionIfExists', true);`, matlab output the following error

`Can't load '/home/cuilab/matlabR2017b/bin/glnxa64/libmwdastudio.so': /lib/x86_64-linux-gnu/libfontconfig.so.1: undefined symbol:
FT_Done_MM_Var`

**Comment by rdiggelmann** [comment]
Has this issue been resolved?

Maybe check out this page: https://ch.mathworks.com/matlabcentral/answers/361053-can-t-reload-usr-local-matlab-r2017b-bin-glnxa64-libmwdastudio-so

**Comment by somalcy** [comment]
Yes, thanks for your response. I removed ​`libmwdastudio.so` in `./bin` and it worked. 

I find the ram is not enough in some leg's processing. I changed the `chunksize` but this problem still happened. So how to handle it during multi-processing?

**Comment by rdiggelmann** [comment]
1) I'd use at least 16GB of memory, preferably more. Usually, we use linux servers with 64GB of RAM in our standard processing pipeline.
With `chunkSize=500000`, I can run the preprocessor without major problems on my 2013 MacBook Pro (for 1024-channel MEA data). But Macs can use their SSD to offload memory when necessary, so I can't guarantee that the situation is similar on a different OS.

2) In the meantime, I committed a couple of changes to the preprocessor to improve how the mean activity over all channels is subtracted from each individual channel. This shouldn't have any effect on most data, but it can improve the situation where the noise over all channels does not have the same amplitude on each channel. In the same process, I added a few minor memory management improvements. I hope this helps.

**Comment by somalcy** [comment]
I used a 64GB RAM ubuntu workstation and my raw data was derived from a 256 channel blackrock recording system (over 100GB). The error (short of RAM) occurred during running `HDSorting.sort('sortingMode', 'local_parfor');`. The `preprocessor` worked well in my project.
